apiVersion: apps/v1
kind: Deployment
metadata:
  name: advert-classifier
  namespace: default
  labels:
    app: advert-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advert-classifier
  template:
    metadata:
      labels:
        app: advert-classifier
    spec:
      containers:
      - name: tf-serving
        image: "tensorflow/serving"
        args:
        - "--model_name=$(MODEL_NAME)"
        - "--model_base_path=$(MODEL_PATH)"
        envFrom:
        - configMapRef:
            name: tfserving-configs
        imagePullPolicy: IfNotPresent
        readinessProbe:
          tcpSocket:
            port: 8500
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 10
        ports:
        - name: http
          containerPort: 8501
          protocol: TCP
        - name: grpc
          containerPort: 8500
          protocol: TCP
        resources:
          requests:
            cpu: "3"
            memory: 4Gi
