name: advert-pipeline-workflow

on:
  push:
    branchs:
      - 'main'
      - 'develop'
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
    paths:
      - 'pipelines/advert_pipeline/**'
      - '!pipelines/advert_pipeline/dashboard/**'
      - '!pipelines/advert_pipeline/deployment/**'
      - '!pipelines/advert_pipeline/orchestration/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: pipelines/advert_pipeline/

    env:
      ENDPOINT: ${{ secrets.ENDPOINT }}

    # TODO: 작동 테스트 확인 필요
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
      # TODO: 도커 쓰는 방법 생각
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade "tfx[kfp]<2"
          pip install python-dotenv
      # TODO: 테스트 functions 추가
      -
        name: Test codes
        run: |
          python -m models.preprocessing_test
      -
        name: Update pipelines
        run: |
          tfx pipeline update --pipeline-path=kubeflow_runner.py --endpoint=$ENDPOINT --build-image
